
#CREATE TABLE admin(id INT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(50) NOT NULL UNIQUE, password CHAR(60) NOT NULL);

#CREATE TABLE school(id INT PRIMARY KEY AUTO_INCREMENT, schoolName VARCHAR(100) NOT NULL UNIQUE, loginEmail VARCHAR(50) NOT NULL UNIQUE, password CHAR(60) NOT NULL);

#CREATE TABLE subject(id INT PRIMARY KEY AUTO_INCREMENT, subjectName VARCHAR(50) NOT NULL UNIQUE);

#CREATE TABLE rubric(id INT PRIMARY KEY AUTO_INCREMENT, rubricName VARCHAR(10) NOT NULL UNIQUE);

#CREATE TABLE subjectStructure(id INT PRIMARY KEY AUTO_INCREMENT, schoolId INT NOT NULL, subjectId INT NOT NULL, std TINYINT NOT NULL, rubricId INT NOT NULL, totalMarks SMALLINT DEFAULT 0);
#ALTER TABLE subjectStructure ADD CONSTRAINT ss_school_fk FOREIGN KEY(schoolId) REFERENCES school(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE subjectStructure ADD CONSTRAINT ss_subject_fk FOREIGN KEY (subjectId) REFERENCES subject(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE subjectStructure ADD CONSTRAINT ss_rubric_fk FOREIGN KEY (rubricId) REFERENCES rubric(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE subjectstructure ADD CONSTRAINT unique_subject UNIQUE(schoolId,subjectId,rubricId,std);

#CREATE TABLE student(id INT PRIMARY KEY AUTO_INCREMENT, GRN SMALLINT NOT NULL, schoolId INT NOT NULL, firstName VARCHAR(30) NOT NULL, middleName VARCHAR(30) NOT NULL, lastName VARCHAR(30) NOT NULL, gender CHAR DEFAULT 'M');
#ALTER TABLE student ADD CONSTRAINT student_school_fk FOREIGN KEY(schoolId) REFERENCES school(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE student ADD CONSTRAINT unique_student UNIQUE(GRN,schoolId);
  
#CREATE TABLE studentHistory(id INT PRIMARY KEY AUTO_INCREMENT, studentId INT NOT NULL, academicYear YEAR NOT NULL, std TINYINT NOT NULL, studentDiv CHAR NOT NULL, rollNo TINYINT NOT NULL);
#ALTER TABLE studentHistory ADD CONSTRAINT sh_student_fk FOREIGN KEY(studentId) REFERENCES student(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE studentHistory ADD CONSTRAINT unique_sh UNIQUE(studentId,academicYear);

#CREATE TABLE result(id INT PRIMARY KEY AUTO_INCREMENT, historyId INT NOT NULL, subjStructId INT NOT NULL, semester BOOL NOT NULL, marksObtained FLOAT DEFAULT 0.0);
#ALTER TABLE result ADD CONSTRAINT result_history_fk FOREIGN KEY(historyId) REFERENCES studentHistory(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE result ADD CONSTRAINT result_subjstr_fk FOREIGN KEY(subjStructId) REFERENCES subjectStructure(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE result ADD CONSTRAINT unique_result UNIQUE(historyId, subjStructId,semester);

#CREATE TABLE attendance(id INT PRIMARY KEY AUTO_INCREMENT, historyId INT NOT NULL, semester BOOL NOT NULL, month TINYINT NOT NULL, attended TINYINT NOT NULL, total TINYINT NOT NULL);
#ALTER TABLE attendance ADD CONSTRAINT attendance_history_fk FOREIGN KEY(historyId) REFERENCES studentHistory(id) ON DELETE CASCADE ON UPDATE CASCADE;
#ALTER TABLE attendance ADD CONSTRAINT unique_history UNIQUE(historyId,semester,MONTH);



